### ISSUE TITLE
This just doesn't work.

### ISSUE THREAD

**Issue by andrejpodzimek** [Davidebyzero/Snipes#10]
One possible outcome is an infinite `nanosleep()` loop:

```
nanosleep({tv_sec=0, tv_nsec=1000000}, 0x7ffeaaa664c0) = 0
```

Another possible outcome is [this segfault](https://github.com/Davidebyzero/Snipes/files/4604570/shithappens.txt).

I recall playing Snipes on a PC XT deep in the past and it was more fun back then, TBH.

**Comment by CyberShadow** [comment]
My best guess is that something is broken with your SDL version or audio. The segfault stack trace might be more helpful than strace output.

If your distribution / audio driver is not cooperating, you might have better luck running a Windows build under Wine.
